# Generated by Django 3.2.6 on 2021-08-28 04:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_rename_registereduser_siteuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteUser',
            new_name='UserProfile',
        ),
    ]
